# Page settings

baseURL = "https://ngmy.github.io/resume/"
languageCode = "ja"
title = "永宮悠大の職務経歴書"
theme = "hugo-devresume-theme"
googleAnalytics = "G-20TT5CYF3T"
defaultContentLanguage = "ja"






[params]
    author = "永宮 悠大"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "<ruby>永宮<rt>ながみや<rt></ruby>&nbsp;<ruby>悠大<rt>ゆうた</rt></ruby>"
        tagline = "Webエンジニア"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "東京都"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "090 5759 5237"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "y.nagamiya@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://ngmy.github.io/"
        text = "ngmy.github.io"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "テクニカル"
        [[params.skills.list.items]]
        details = "PHP/Laravel"
        [[params.skills.list.items]]
        details = "JavaScript/jQuery/Angular/React/Vue"
        [[params.skills.list.items]]
        details = "Docker/Kubernetes"
        [[params.skills.list.items]]
        details = "チューニング（nginx/Apache/php.ini）"
        [[params.skills.list.items]]
        details = "MySQL"
        [[params.skills.list.items]]
        details = "Redis/memcached"
        [[params.skills.list.items]]
        details = "継続的インテグレーション/ユニットテスト/静的解析/開発環境整備"
        [[params.skills.list.items]]
        details = "AWS/GCP"
        [[params.skills.list.items]]
        details = "オブジェクト指向設計/ドメイン駆動設計"
        [[params.skills.list.items]]
        details = "SQL/データベース設計"
        [[params.skills.list.items]]
        details = "アーキテクチャー設計"
        [[params.skills.list.items]]
        details = "リファクタリング/レガシーコード改善"
        [[params.skills.list.items]]
        details = "プロジェクトマネージメント"

        [[params.skills.list]]
        title = "ポータブル"
        [[params.skills.list.items]]
        details = "計画立案能力"
        [[params.skills.list.items]]
        details = "課題遂行能力"
        [[params.skills.list.items]]
        details = "状況対応能力"
        [[params.skills.list.items]]
        details = "スケジュール管理能力"
        [[params.skills.list.items]]
        details = "問題解決能力"
        [[params.skills.list.items]]
        details = "プロジェクトマネージメント力"
        [[params.skills.list.items]]
        details = "業務改善能力"






    [params.education]
        enable = true

        [[params.education.list]]
        degree = "修士（工学）"
        university = "群馬大学 大学院工学研究科 情報工学専攻"
        dates = "2006 - 2008"
        [[params.education.list]]
        degree = "学士（工学）"
        university = "群馬大学 工学研究科 情報工学科"
        dates = "2002 - 2006"








#    [params.awards]
#        enable = true
#
#        [[params.awards.list]]
#        name = "Award Lorem Ipsum"
#        body = "Microsoft lorem ipsum"
#        date = "2019"
#        [[params.awards.list]]
#        name = "Award Donec Sodales"
#        body = "Oracle Aenean"
#        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "日本語"
        level = "母語語"
        [[params.languages.list]]
        name = "英語"
        level = "ドキュメントが読める"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "クライミング"
        [[params.interests.list]]
        name = "囲碁"








    [params.summary]
        enable = true
        text = "10年以上の経験を持ち、PHPとオブジェクト指向設計を愛するWebエンジニア。大手システムインテグレーターでのかっちりした受託開発と、1→10フェーズのスタートアップでのスピード感ある自社サービス開発の両方の経験を持つ。前職ではPHPとLaravelのテックリードを務め開発をリードした。計画立案能と課題遂行が得意で、納期と品質の期待値を外さないことに長けている。特に好きな分野は「複雑な業務をシステムに落とし込むこと」と「静的解析・ユニットテスト・継続的インテグレーション等の生産性向上の仕組みづくり」。重視することは「自分が開発を楽しむこと」と「プロとして納期と品質の期待値を外さず顧客に価値を届けること」。最大10人のプロジェクトマネージメント経験を持つが、マネージメントより自分で手を動かして開発する仕事が好き。PHPが好きで得意だが、大学・大学院でプログラミングとコンピューターサイエンスを学んだバックグラウンドを持ち、PHP以外にも複数の動的型付け・静的型付け言語の経験を持つ。"








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "テックリード"
        dates = "2016 - 2020"
        company = "株式会社ホワイトプラス"
        details = "サーバーサイドエンジニアとして自社サービスをドメイン駆動設計で開発しながら、PHPのテックリードとしてユニットテスト・静的解析・継続的インテグレーションの導入やシステムのあるべき姿のデザインおよびその実現に向けた開発リードを務める。 "
        [[params.experience.list.items]]
        details = "PHPのバージョンアップ（5.5→7.2）やLaravelのバージョンアップ（4.2→5.5→6）、PHP環境のDocker化を行ったり、インフラ担当と協力してのKubernetes化・継続的デリバリー基盤の構築を行い、生産性や開発速度の向上させた"
        [[params.experience.list.items]]
        details = "継続的インテグレーション環境の構築・ユニットテスト・静的解析の導入（PHPStan、PHP_CodeSniffer等）、チームへの展開を行い、堅牢化した"
        [[params.experience.list.items]]
        details = "PHP/Laravel+オブジェクト指向設計・ドメイン駆動設計を用いたサーバーサイドの開発（PHP/Laravel/MySQL）をチームと実践した"
        [[params.experience.list.items]]
        details = "PHP/Laravelの開発基盤の整備、パフォーマンスチューニング、コードやデータベースのリファクタリング、共通部品の開発およびチームへの展開やコードレビュー・ペアプログラミングを通じてPHPの開発をリードした"
        [[params.experience.list.items]]
        details = "エンジニア採用および面談時のペアプログラミングを提案し実践し、優れた人材の採用に成功した。また、新人教育プログラムの作成・新入社員のメンターも行った"

        [[params.experience.list]]
        title = "アーキテクト/プレイングマネージャー"
        dates = "2010 - 2016"
        company = "株式会社日立ソフトウェアエンジニアリング（現・株式会社日立ソリューションズ）"
        details = "システムアーキテクトとして高負荷・高トラフィックなニュースサイトのアーキテクチャー設計および開発リードを務める。さらにプレイングマネージャーとして納品後の運用において最大10人のチームのプロジェクトマネージメントおよび開発リードを務める。"
        [[params.experience.list.items]]
        details = "パフォーマンス、スケーラビリティー、開発コストを考慮したアーキテクチャー設計を行い、秒間3,000リクエスト、月間10億PVを捌くシステムを構築し運用"
        [[params.experience.list.items]]
        details = "Web API、サーバーサイド、フロントエンド、共通部品やフレームワークまわりの開発を行うともに、コードレビューを通してチームの開発をリード"
        [[params.experience.list.items]]
        details = "継続的インテグレーション、ユニットテスト、静的解析を導入し、バグの発生の低減や改修コストの低減を達成"
        [[params.experience.list.items]]
        details = "パフォーマンスやリソースの監視設計・実装を行い、SQLやPHP、Webサーバー（Apache）のパフォーマンスのチューニングを行うことで、安定した運用を実現"
        [[params.experience.list.items]]
        details = "要件定義・工数見積もり・顧客との折衝を行いながら、プロジェクトマネージメントを行い、最大10人の社員・協力会社からなるチームを回した"

        [[params.experience.list]]
        title = "サーバーサイドエンジニア"
        dates = "2008 - 2010"
        company = "株式会社日立ソフトウェアエンジニアリング（現・株式会社日立ソリューションズ）"
        details = "サーバーサイドエンジニアとして動的型付けと静的型付けの両方の言語で様々なWebシステムの開発を経験。"
        [[params.experience.list.items]]
        details = "Q&Aコミュニティーサービス（PHP）、健康機器測定データ連携サービス（Java）、ケーブルテレビ局の顧客管理システム（Perl）、検索エンジンの形態素解析モジュール（C/Ruby）等を開発"
        [[params.experience.list.items]]
        details = "プログラミング以外にも要件定義から納品までの全工程を経験"











    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Webloyer"
        meta = "オープンソース"
        tagline = "PHP製のデプロイツール「Deployer」のWebユーザーインターフェイス。Laravelを使用してドメイン駆動設計で実装。 <a class=\"resume-link\" href=\"https://github.com/ngmy/webloyer\" target=\"_blank\">https://github.com/ngmy/webloyer</a>"

        [[params.projects.list]]
        title = "PHP WebDAV Client"
        meta = "オープンソース"
        tagline = "PHP用のWebDAVクライアント。PSR-7（HTTPメッセージインターフェイス）、PSR-17（HTTPファクトリー）、PST-18（HTTPクライアント）を使用して実装。 <a class=\"resume-link\" href=\"https://github.com/ngmy/l4-dav\" target=\"_blank\">https://github.com/ngmy/l4-dav</a>"










    [params.information]
        enable = true

        [[params.information.list]]
        title = "資格"
        [[params.information.list.items]]
        details = "2020 · PHP7技術者認定初級試験"
        [[params.information.list.items]]
        details = "2015 · システムアーキテクト試験"
        [[params.information.list.items]]
        details = "2011 · 情報セキュリティスペシャリスト試験（現・情報処理安全確保支援士試験）"
        [[params.information.list.items]]
        details = "2011 · LPIC-1"
        [[params.information.list.items]]
        details = "2008 · ソフトウェア開発技術者試験（現・応用情報技術者試験）"
        [[params.information.list.items]]
        details = "2007 · 基本情報技術者試験"

        [[params.information.list]]
        title = "関連記事"
        [[params.information.list.items]]
        details = "【社員インタビュー#エンジニア】WEBだけでなくリアルなサービスが絡んでいるのが面白い | ホワプラSTYLE · <a class=\"resume-link\" href=\"https://style.wh-plus.co.jp/interview-nagamiyayuta/\" target=\"_blank\">https://style.wh-plus.co.jp/interview-nagamiyayuta/</a>"







    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/ngmy"
        title = "ngmy"
        [[params.social.list]]
        icon = "icon-qiita"
        url = "https://qiita.com/ngmy"
        title = "@ngmy"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "https://twitter.com/ngmy"
        title = "@ngmy"





