# Page settings

defaultContentLanguage = "ja"

baseURL = "https://ngmy.github.io/resume/"
languageCode = "ja"
title = "職務経歴書（永宮 悠大）"
theme = "hugo-devresume-theme"
googleAnalytics = "G-20TT5CYF3T"






[params]
    author = "永宮 悠大"
    description = "ngmy（永宮悠大）の職務経歴書です。"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "<ruby>永宮<rt>ながみや<rt></ruby>&nbsp;<ruby>悠大<rt>ゆうた</rt></ruby>"
        tagline = "Webエンジニア"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "東京都"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:09057595237"
        text = "090 5759 5237"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:y.nagamiya+work@gmail.com"
        text = "y.nagamiya+work@gmail.com"
        [[params.contact.list]]
        icon = "fab fa-skype"
        url = "skype:live:y.nagamiya?call"
        text = "live:y.nagamiya"
        [[params.contact.list]]
        icon = "svg-inline--fa icon-pay-career"
        url = "https://pay-career.com/spot_request/2033945709/"
        text = "pay-career.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://ngmy.github.io/"
        text = "ngmy.github.io"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "ハードスキル"
        [[params.skills.list.items]]
        details = "プログラミング言語：PHP、JavaScript"
        [[params.skills.list.items]]
        details = "フレームワーク・ライブラリー：Laravel、CakePHP、Slim、Symfonyコンポーネント、Vue.js、React、Angular、jQuery"
        [[params.skills.list.items]]
        details = "データベース：MySQL、Redis、memcached、Firestore"
        [[params.skills.list.items]]
        details = "Webサーバー：nginx、Apache"
        [[params.skills.list.items]]
        details = "テストツール：PHPUnit、Selenium"
        [[params.skills.list.items]]
        details = "静的解析ツール：PHPStan、Psalm、PHP_CodeSniffer、PHP CS Fixer、PHPMD"
        [[params.skills.list.items]]
        details = "コンテナーツール：Docker、Kubernetes"
        [[params.skills.list.items]]
        details = "バージョン管理ツール：Git（GitHub、GitLab）"
        [[params.skills.list.items]]
        details = "継続的インテグレーションサービス：GitHub Actions、CircleCI、Travis CI"
        [[params.skills.list.items]]
        details = "クラウドサービス：AWS、GCP、Heroku、Firebase"
        [[params.skills.list.items]]
        details = "OS：Windows（WSL 2）、Mac、Linux"
        [[params.skills.list.items]]
        details = "エディター：Vim"
        [[params.skills.list.items]]
        details = "Web開発（特にサーバーサイド）"
        [[params.skills.list.items]]
        details = "オブジェクト指向設計、ドメイン駆動設計"
        [[params.skills.list.items]]
        details = "アーキテクチャー設計"
        [[params.skills.list.items]]
        details = "SQL、関係データベース設計"
        [[params.skills.list.items]]
        details = "継続的インテグレーション・ユニットテスト・静的解析の仕組みづくり"
        [[params.skills.list.items]]
        details = "リファクタリング、レガシーコード改善"
        [[params.skills.list.items]]
        details = "コードリーディング、業務理解"
        [[params.skills.list.items]]
        details = "要件定義、工数見積、プロジェクトマネージメント、顧客折衝"
        [[params.skills.list.items]]
        details = "ドキュメント作成"
        [[params.skills.list.items]]
        details = "コードレビュー"
        [[params.skills.list.items]]
        details = "トラブルシューティング"

        [[params.skills.list]]
        title = "ソフトスキル"
        [[params.skills.list.items]]
        details = "課題発見能力"
        [[params.skills.list.items]]
        details = "問題解決能力"
        [[params.skills.list.items]]
        details = "情報収集能力"
        [[params.skills.list.items]]
        details = "洞察力"
        [[params.skills.list.items]]
        details = "自走力"
        [[params.skills.list.items]]
        details = "プロ意識"
        [[params.skills.list.items]]
        details = "細部への注意"
        [[params.skills.list.items]]
        details = "粘り強さ"
        [[params.skills.list.items]]
        details = "学習意欲"




    [params.education]
        enable = true

        [[params.education.list]]
        degree = "修士（工学）"
        university = "群馬大学 大学院工学研究科 情報工学専攻"
        dates = "2006年～2008年"
        [[params.education.list]]
        degree = "学士（工学）"
        university = "群馬大学 工学研究科 情報工学科"
        dates = "2002年～2006年"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "日本語"
        level = "母語語"
        [[params.languages.list]]
        name = "英語"
        level = "ドキュメントが読める"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "ロッククライミング"
        [[params.interests.list]]
        name = "囲碁"
        [[params.interests.list]]
        name = "Web開発、OSS開発"








    [params.summary]
        enable = true
        text = "10年以上のWeb開発経験を持つWebエンジニア。PHPとドメイン駆動設計が好き。大手システムインテグレーターでの受託開発経験と1→10フェーズのスタートアップでの自社サービス開発経験の両方を持つ。前職ではサーバーサイドのテックリードを務めた。PHP以外にも動的言語と静的言語の両方の使用経験を持ち、大学・大学院でコンピューターサイエンスを学んだバックグラウンドを持つ。PHPとドメイン駆動設計の技術で開発をリードできるポジションで働きたい。最大10人のプロジェクトのマネージメント経験も持つが、マネージメントより自分で手を動かす仕事をしたい。好きで得意な仕事は「複雑な業務を設計に落とし込むこと」と「継続的インテグレーション・ユニットテスト・静的解析の仕組みづくり」。仕事をする上で大切にしている価値観は「自分が楽しむこと」と「納期と品質の期待値を外すことなく顧客に価値を届けること」。"








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "フリーランス"
        dates = "2021年6月～現在"
        [[params.experience.list.items]]
        details = "マーケティング系スタートアップへの開発支援<ul><li>SaaS型のLINE公式アカウント自動化ツールに対して、LINE APIを使用した設定機能や、ビジネス指標の可視化機能等の追加開発を行った（laravel-admin、React）</li></ul>"
        [[params.experience.list.items]]
        details = "物流系スタートアップへの開発支援<ul><li>SaaS型の倉庫管理システムに対してFedEx APIを使用した海外発送機能等の追加開発を行った（Laravel、React）</li></ul>"
        [[params.experience.list.items]]
        details = "EC系スタートアップへの開発支援<ul><li>ECサイトに対してドメイン駆動設計で追加開発を行った（CakePHP、Vue.js）</li></ul>"

        [[params.experience.list]]
        title = "個人開発者"
        dates = "2020年8月～現在"
        [[params.experience.list.items]]
        details = "WebサービスやWebアプリケーションの開発・運営や、OSSの開発・公開を行っている"

        [[params.experience.list]]
        title = "テックリード"
        dates = "2016年10月～2020年7月"
        company = "株式会社ホワイトプラス"
        [[params.experience.list.items]]
        details = "PHP・Laravelの技術でサーバーサイド開発やアーキテクチャー設計をリードした"
        [[params.experience.list.items]]
        details = "PHP・Laravelのバージョンアップをリードした"
        [[params.experience.list.items]]
        details = "ドメイン駆動設計を導入・実践した"
        [[params.experience.list.items]]
        details = "継続的インテグレーション・ユニットテスト・静的解析の仕組みを構築した<ul><li>[リネットのPHPアプリケーションのCIを10倍速くするためにやったこと](https://qiita.com/ngmy/items/0821d9c56834b6b15a5f)</li><li>[PHPStanによる静的解析をLaravelアプリケーションに導入するためにやったこと](https://qiita.com/ngmy/items/1a8ef21c76d74c1d4dfe)</li></ul>"
        [[params.experience.list.items]]
        details = "販売管理システム・倉庫管理システム・顧客管理システム・請求管理システム等を開発した"
        [[params.experience.list.items]]
        details = "ヤマトB2・エコ配等を利用した発送機能を開発した"
        [[params.experience.list.items]]
        details = "エンジニア採用やジュニアエンジニアのメンターを担当した"
        [[params.experience.list.items]]
        details = "エンジニアが不足していた時期は、一つのサービスのフロントエンドからサーバーサイドまでのすべてを一人で開発した"

        [[params.experience.list]]
        title = "プレイングマネージャー"
        dates = "2013年1月～2016年9月"
        company = "株式会社日立ソフトウェアエンジニアリング（現・株式会社日立ソリューションズ）"
        [[params.experience.list.items]]
        details = "大規模ニュースサイトを運用・保守した"
        [[params.experience.list.items]]
        details = "顧客折衝や最大10人のプロジェクトのマネージメントを行った"
        [[params.experience.list.items]]
        details = "性能監視の設計・実装や性能改善を行い、月間PV数が1.8億から10億へ増加する中、平均レスポンスタイム200ミリ秒以下を実現した"
        [[params.experience.list.items]]
        details = "PHP・Apache・MySQL・memcachedを使用した開発をリードした"

        [[params.experience.list]]
        title = "アーキテクト"
        dates = "2012年7月～2012年12月"
        company = "株式会社日立ソフトウェアエンジニアリング（現・株式会社日立ソリューションズ）"
        [[params.experience.list.items]]
        details = "大規模ニュースサイトのアーキテクチャーを設計した"
        [[params.experience.list.items]]
        details = "継続的インテグレーション・ユニットテスト・静的解析の仕組みを構築した"
        [[params.experience.list.items]]
        details = "PHP・Apache・MySQL・memcachedを使用してアーキテクチャーを実装した"

        [[params.experience.list]]
        title = "サーバーサイドエンジニア"
        dates = "2008年4月～2012年6月"
        company = "株式会社日立ソフトウェアエンジニアリング（現・株式会社日立ソリューションズ）"
        [[params.experience.list.items]]
        details = "様々な言語で様々なWebサービス・Webアプリケーションを開発した"
        [[params.experience.list.items]]
        details = "要件定義から納品までの全工程を経験した"











    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "[Webloyer](https://github.com/ngmy/webloyer)"
        meta = "OSS"
        tagline = "PHP製のデプロイツール「Deployer」のWebユーザーインターフェイス。Laravelを使用してドメイン駆動設計で開発している。"

        [[params.projects.list]]
        title = "[PHP WebDAV Client](https://github.com/ngmy/l4-dav)"
        meta = "OSS"
        tagline = "PHP用のWebDAVクライアント。PSR-7（HTTPメッセージインターフェイス）、PSR-17（HTTPファクトリー）、PSR-18（HTTPクライアント）を使用して開発している。"










    [params.information]
        enable = true

        [[params.information.list]]
        title = "資格"
        [[params.information.list.items]]
        details = "2020年：PHP7技術者認定初級試験"
        [[params.information.list.items]]
        details = "2015年：システムアーキテクト試験"
        [[params.information.list.items]]
        details = "2011年：情報セキュリティスペシャリスト試験（現・情報処理安全確保支援士試験）"
        [[params.information.list.items]]
        details = "2011年：Linux Professional Institute Certification Level 1（LPIC-1）"
        [[params.information.list.items]]
        details = "2008年：ソフトウェア開発技術者試験（現・応用情報技術者試験）"
        [[params.information.list.items]]
        details = "2007年：基本情報技術者試験"

        [[params.information.list]]
        title = "人となり"
        [[params.information.list.items]]
        details = "[【社員インタビュー#エンジニア】WEBだけでなくリアルなサービスが絡んでいるのが面白い | ホワプラSTYLE](https://style.wh-plus.co.jp/interview-nagamiyayuta/)"







    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/ngmy"
        title = "ngmy"
        [[params.social.list]]
        icon = "svg-inline--fa icon-qiita"
        url = "https://qiita.com/ngmy"
        title = "@ngmy"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "https://twitter.com/ngmy"
        title = "@ngmy"





    [params.footer]
        copyright = "[永宮 悠大](https://ngmy.github.io/)"
