# Page settings

defaultContentLanguage = "ja"

baseURL = "https://ngmy.github.io/resume/"
languageCode = "ja"
title = "永宮悠大の職務経歴書"
theme = "hugo-devresume-theme"
googleAnalytics = "G-20TT5CYF3T"






[params]
    author = "永宮 悠大"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "<ruby>永宮<rt>ながみや<rt></ruby>&nbsp;<ruby>悠大<rt>ゆうた</rt></ruby>"
        tagline = "Webエンジニア"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "東京都"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:09057595237"
        text = "090 5759 5237"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:y.nagamiya@gmail.com"
        text = "y.nagamiya@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://ngmy.github.io/"
        text = "ngmy.github.io"
        [[params.contact.list]]
        icon = "svg-inline--fa icon-pay-career"
        url = "https://pay-career.com/spot_request/2033945709/"
        text = "pay-career.com"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "テクニカル"
        [[params.skills.list.items]]
        details = "<strong>プログラミング言語：</strong>PHP、JavaScript、Bash"
        [[params.skills.list.items]]
        details = "<strong>フレームワーク&ライブラリー：</strong>Laravel、Symfonyコンポーネント、jQuery、Vue.js、React、Angular"
        [[params.skills.list.items]]
        details = "<strong>関係データベース：</strong>MySQL"
        [[params.skills.list.items]]
        details = "<strong>NoSQLデータベース：</strong>Redis、memcached"
        [[params.skills.list.items]]
        details = "<strong>Webサーバー：</strong>nginx、Apache"
        [[params.skills.list.items]]
        details = "<strong>テストツール：</strong>PHPUnit、Selenium"
        [[params.skills.list.items]]
        details = "<strong>静的解析ツール：</strong>PHPStan、Psalm、PHP_CodeSniffer、PHP CS Fixer、PHPMD"
        [[params.skills.list.items]]
        details = "<strong>仮想化ツール：</strong>Docker、Kubernetes"
        [[params.skills.list.items]]
        details = "<strong>継続的インテグレーションサービス：</strong>GitHub Actions、CircleCI、Travis CI"
        [[params.skills.list.items]]
        details = "<strong>クラウドサービス：</strong>Amazon Web Services（AWS）、Google Cloud Platform（GCP）"
        [[params.skills.list.items]]
        details = "<strong>開発環境：</strong>Windows Subsystem for Linux 2 (WSL 2) 、Mac、Linux"
        [[params.skills.list.items]]
        details = "<strong>その他：</strong>Git、GitHub、Vim"

        [[params.skills.list]]
        title = "プロフェッショナル"
        [[params.skills.list.items]]
        details = "サーバーサイド開発"
        [[params.skills.list.items]]
        details = "オブジェクト指向設計・ドメイン駆動設計"
        [[params.skills.list.items]]
        details = "アーキテクチャー設計"
        [[params.skills.list.items]]
        details = "SQL・データベース設計"
        [[params.skills.list.items]]
        details = "継続的インテグレーション・ユニットテスト・静的解析"
        [[params.skills.list.items]]
        details = "リファクタリング・レガシーコード改善"
        [[params.skills.list.items]]
        details = "要件定義・工数見積・プロジェクトマネージメント"
        [[params.skills.list.items]]
        details = "既存システムの理解が早い"
        [[params.skills.list.items]]
        details = "わかりやすいドキュメントを書ける"





    [params.education]
        enable = true

        [[params.education.list]]
        degree = "修士（工学）"
        university = "群馬大学 大学院工学研究科 情報工学専攻"
        dates = "2006 - 2008"
        [[params.education.list]]
        degree = "学士（工学）"
        university = "群馬大学 工学研究科 情報工学科"
        dates = "2002 - 2006"








#    [params.awards]
#        enable = true
#
#        [[params.awards.list]]
#        name = "Award Lorem Ipsum"
#        body = "Microsoft lorem ipsum"
#        date = "2019"
#        [[params.awards.list]]
#        name = "Award Donec Sodales"
#        body = "Oracle Aenean"
#        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "日本語"
        level = "母語語"
        [[params.languages.list]]
        name = "英語"
        level = "ドキュメントが読める"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "クライミング"
        [[params.interests.list]]
        name = "囲碁"








    [params.summary]
        enable = true
        text = "10年以上の経験を持ち、Webサービスと業務システムの両方の開発経験を持つ、PHPとオブジェクト指向設計を愛するWebエンジニア。大手システムインテグレーターでのかっちりとした受託開発と、1→10フェーズのスタートアップでのスピード感あふれる自社サービス開発の両方の経験を持つ。前職ではPHPとLaravelのテックリードを務め開発をリードした。好きで得意な仕事は「複雑な業務をシステムに落とし込むこと」と「静的解析、ユニットテスト、継続的インテグレーション等の品質・生産性の向上のための仕組みづくり」。仕事をする上で大切にしていることは「自分が楽しむこと」と「納期と品質の期待値を外さず顧客に価値を届けること」。最大10人のプロジェクトマネージメント経験を持つが、マネージメントより自分で手を動かして開発する方が好き。大学・大学院でプログラミングとコンピューターサイエンスを学んだバックグラウンドを持ち、PHP以外にも動的型付けと静的型付けの両方の言語の経験を持つ。"








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "テックリード"
        dates = "2016 - 2020"
        company = "株式会社ホワイトプラス"
        details = "PHPとLaravelのテックリードを務め、自社サービスの開発をリードした。 "
        [[params.experience.list.items]]
        details = "システムの未来像を描き、PHPとLaravelの継続的なバージョンアップ、パフォーマンスチューニング、コードやデータベースのリファクタリング、共通部品の開発、コードレビュー、ペアプログラミング、知識やノウハウの展開等を行うことで、開発をリードした"
        [[params.experience.list.items]]
        details = "継続的インテグレーション、ユニットテスト、静的解析（PHPStan、PHP_CodeSniffer等）を導入することで、チームの品質・生産性を向上させた"
        [[params.experience.list.items]]
        details = "PHPの実行環境をDocker化し、さらにインフラエンジニアと協力してKubernetesを導入することで、インフラの柔軟性を向上させた"
        [[params.experience.list.items]]
        details = "開発チームと協力して生産管理システムや原価管理システムをPHPとLaravelを使用してドメイン駆動設計で開発することで、洗練されたシステムを構築する同時に、生産部・経理部の課題を解決し目標達成に貢献した"
        [[params.experience.list.items]]
        details = "エンジニアの採用面談を担当し、面談時のペアプログラミングを提案・実践することで、即戦力の採用に成功した"
        [[params.experience.list.items]]
        details = "新人教育プログラムの作成・実施したり新人のメンターを担当することで、新人教育プログラムの作成・実施したり新人のメンターを担当することで、新人を育成した"

        [[params.experience.list]]
        title = "アーキテクト・プレイングマネージャー"
        dates = "2012 - 2016"
        company = "株式会社日立ソフトウェアエンジニアリング（現・株式会社日立ソリューションズ）"
        details = "高負荷・高トラフィックなニュースサイトを受託開発・運用した。開発ではアーキテクトを務め、アーキテクチャーを設計し開発をリードした。納品後の運用ではプレイングマネージャーを務め、最大10人のプロジェクトをマネージメントしながら開発をリードした。"
        [[params.experience.list.items]]
        details = "パフォーマンス、スケーラビリティー、開発コストを考慮したアーキテクチャー設計を行うことで、顧客の要件を満足するシステムを納期までに納品できた（サービスの成長に応じてシステムを改善し続けることで、最終的に秒間3,000リクエスト、月間10億PVのアクセスに耐えるシステムにできた）"
        [[params.experience.list.items]]
        details = "Web API・サーバーサイド・フロントエンド・共通部品・フレームワークまわりの開発、メンバーへのコードレビューを行うことで、開発をリードした"
        [[params.experience.list.items]]
        details = "継続的インテグレーション、ユニットテスト、静的解析を導入することで、チームの品質・生産性を向上させた"
        [[params.experience.list.items]]
        details = "パフォーマンス・リソースの監視の設計・実装を行い、Webサーバー（Apache）、アプリケーション（PHP）、データベース・SQL（MySQL）のパフォーマンスをチューニングすることで、3年以上の安定した運用を実現した"
        [[params.experience.list.items]]
        details = "納品後の運用において、要件定義・工数見積もり・顧客との折衝を行いながら最大10人の社員・協力会社社員のプロジェクトマネージメントを行うことで、3年以上契約を継続させ、自社の利益および顧客のサービスの成長を達成できた（月間1.8億PV→月間10PV）"

        [[params.experience.list]]
        title = "サーバーサイドエンジニア"
        dates = "2008 - 2012"
        company = "株式会社日立ソフトウェアエンジニアリング（現・株式会社日立ソリューションズ）"
        details = "サーバーサイドエンジニアを務め、動的型付けと静的型付けの両方の言語で様々なWebシステムを受託開発した。"
        [[params.experience.list.items]]
        details = "Q&Aコミュニティーサービス（PHP）、健康機器測定データプラットフォームおよび健康支援サービス（Java）、ケーブルテレビ局の顧客管理システム（Perl）、検索エンジンの形態素解析モジュール（C・Ruby）等を開発した"
        [[params.experience.list.items]]
        details = "プログラミング以外にも要件定義から納品までの全工程を経験した"











    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Webloyer"
        meta = "オープンソース"
        tagline = "PHP製のデプロイツール「Deployer」のWebユーザーインターフェイス。Laravelを使用してドメイン駆動設計で開発している。 <a class=\"resume-link\" href=\"https://github.com/ngmy/webloyer\" target=\"_blank\">https://github.com/ngmy/webloyer</a>"

        [[params.projects.list]]
        title = "PHP WebDAV Client"
        meta = "オープンソース"
        tagline = "PHP用のWebDAVクライアント。PSR-7（HTTPメッセージインターフェイス）、PSR-17（HTTPファクトリー）、PSR-18（HTTPクライアント）を使用して開発している。 <a class=\"resume-link\" href=\"https://github.com/ngmy/l4-dav\" target=\"_blank\">https://github.com/ngmy/l4-dav</a>"










    [params.information]
        enable = true

        [[params.information.list]]
        title = "資格"
        [[params.information.list.items]]
        details = "2020 · PHP7技術者認定初級試験"
        [[params.information.list.items]]
        details = "2015 · システムアーキテクト試験"
        [[params.information.list.items]]
        details = "2011 · 情報セキュリティスペシャリスト試験（現・情報処理安全確保支援士試験）"
        [[params.information.list.items]]
        details = "2011 · Linux Professional Institute Certification Level 1（LPIC-1）"
        [[params.information.list.items]]
        details = "2008 · ソフトウェア開発技術者試験（現・応用情報技術者試験）"
        [[params.information.list.items]]
        details = "2007 · 基本情報技術者試験"

        [[params.information.list]]
        title = "関連記事"
        [[params.information.list.items]]
        details = "【社員インタビュー#エンジニア】WEBだけでなくリアルなサービスが絡んでいるのが面白い | ホワプラSTYLE · <a class=\"resume-link\" href=\"https://style.wh-plus.co.jp/interview-nagamiyayuta/\" target=\"_blank\">https://style.wh-plus.co.jp/interview-nagamiyayuta/</a>"







    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/ngmy"
        title = "ngmy"
        [[params.social.list]]
        icon = "svg-inline--fa icon-qiita"
        url = "https://qiita.com/ngmy"
        title = "@ngmy"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "https://twitter.com/ngmy"
        title = "@ngmy"





    [params.footer]
        copyright = "[永宮 悠大](https://ngmy.github.io/)"
