# Page settings

defaultContentLanguage = "ja"

baseURL = "https://ngmy.github.io/resume/"
languageCode = "ja_JP"
title = "職務経歴書（永宮 悠大）"
theme = "hugo-devresume-theme"
googleAnalytics = "G-20TT5CYF3T"






[params]
    author = "永宮 悠大"
    description = "永宮悠大の職務経歴書です。"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "<ruby>永宮<rt>ながみや<rt></ruby> <ruby>悠大<rt>ゆうた</rt></ruby>"
        tagline = "フリーランスWebエンジニア"
        avatar = "profile.png"







    [params.contact]
        enable = true
        location = "東京都"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:09057595237"
        text = "090 5759 5237"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:y.nagamiya+work@gmail.com"
        text = "y.nagamiya+work@gmail.com"
        [[params.contact.list]]
        icon = "fab fa-skype"
        url = "skype:live:y.nagamiya?call"
        text = "live:y.nagamiya"
        [[params.contact.list]]
        icon = "svg-inline--fa icon-pay-career"
        url = "https://pay-career.com/spot_request/2033945709/"
        text = "pay-career.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://ngmy.github.io/"
        text = "ngmy.github.io"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "ハードスキル"
        [[params.skills.list.items]]
        details = "経験分野：サーバーサイドメインのWeb開発（15年以上）"
        [[params.skills.list.items]]
        details = "設計手法：オブジェクト指向設計（10年以上）、ドメイン駆動設計（5年以上）"
        [[params.skills.list.items]]
        details = "プログラミング言語：PHP（10年以上）、JavaScript（10年以上）"
        [[params.skills.list.items]]
        details = "フレームワーク：Laravel（10年以上）、CakePHP（1年以上）、Vue.js（3年以上）、React（1年以上）、jQuery（10年以上）"
        [[params.skills.list.items]]
        details = "データベース：MySQL（10年以上）、Redis（5年以上）、memcached（5年以上）、Firestore（1年以上）"
        [[params.skills.list.items]]
        details = "Webサーバー：nginx（5年以上）、Apache（5年以上）"
        [[params.skills.list.items]]
        details = "クラウドプラットフォーム：AWS（5年以上）、GCP（3年以上）、Heroku（3年以上）、Firebase（1年以上）"
        [[params.skills.list.items]]
        details = "開発支援ツール：Git（10年以上）、GitHub（10年以上）、GitLab（1年以上）、GitHub Actions（3年以上）、CircleCI（5年以上）、Travis CI（5年以上）"
        [[params.skills.list.items]]
        details = "テスト・静的解析ツール：PHPUnit（10年以上）、Selenium（3年以上）、PHPStan（5年以上）、Psalm（1年以上）、PHP_CodeSniffer（10年以上）、PHP CS Fixer（3年以上）、PHPMD（10年以上）"
        [[params.skills.list.items]]
        details = "その他開発環境：Docker（5年以上）、WSL（3年以上）、Mac（10年以上）、Linux（10年以上）、Vim（10年以上）"
        [[params.skills.list.items]]
        details = "マネージメント経験：最大10人のプロジェクトのプロジェクトマネージメント（3年以上）"
        [[params.skills.list.items]]
        details = "開発パート経験：要件定義（10年以上）、設計（15年以上）、実装（15年以上）、テスト（15年以上）、運用（10年以上）"
        [[params.skills.list.items]]
        details = "その他開発経験：アーキテクチャー設計、データベース設計、SQLチューニング、レガシーコード改善、コードレビュー、トラブルシューティング、ドキュメント作成、工数見積、継続的インテグレーション・ユニットテスト・静的解析の仕組みづくり"

        [[params.skills.list]]
        title = "ソフトスキル"
        [[params.skills.list.items]]
        details = "課題発見能力、問題解決能力、情報収集能力、洞察力、自走力、プロ意識、細部への注意、粘り強さ、学習意欲"




    [params.education]
        enable = true

        [[params.education.list]]
        degree = "修士（工学）"
        university = "群馬大学 大学院工学研究科 情報工学専攻（現・群馬大学 大学院情報学研究科 情報科学プログラム）"
        dates = "2006年～2008年"
        [[params.education.list]]
        degree = "学士（工学）"
        university = "群馬大学 工学部 情報工学科（現・群馬大学 情報学部 計算機科学プログラム）"
        dates = "2002年～2006年"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "英語"
        level = "ドキュメントが読める"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "クライミング、囲碁、プログラミング"








    [params.summary]
        enable = true
        text = "15年以上のWeb開発経験を持つ、PHPとオブジェクト指向が好きなフリーランスのWebエンジニア。大手SIerでの受託開発経験と1→10フェーズのスタートアップでの自社サービス開発経験の両方を持つ。前職ではPHP・Laravelのテックリード経験も持つ。PHP以外にも動的言語と静的言語の両方の使用経験を持ち、大学・大学院でコンピューターサイエンスを学んだバックグラウンドを持つ。好きな仕事はアプリケーション開発で、特に大所高所のアプリケーションアーキテクチャー設計が好きだが、実際に手を動かす開発作業も好き。仕事をする上で大切にしている価値観は「自分が楽しむこと」と「納期と品質の期待値を外さず顧客に価値を届けること」。"







    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "フリーランスWebエンジニア"
        dates = "2021年6月～現在"
        [[params.experience.list.items]]
        details = """SaaS型業務委託管理システムを提供するスタートアップでの技術課題解決（2023年10月～現在）
        <ul>
          <li>アプリケーションアーキテクチャーの策定</li>
          <li>コーディング規約の策定</li>
          <li>設計・テスト・リファクタリング方針の策定</li>
          <li>継続的インテグレーション環境の構築、静的解析の導入</li>
        </ul>
        """
        [[params.experience.list.items]]
        details = """SaaS型CRMツールを提供するスタートアップのCTO直下でのPoC（2022年10月～2023年9月）
        <ul>
          <li>API開発でのスキーマ駆動開発の導入・実践（Laravel、OpenAPI Generator）</li>
          <li>分析用データレイクの設計・構築（Amazon Athena、AWS Lambda）</li>
          <li>全文検索機能の検証（Laravel Scout、Algolia）</li>
          <li>各種プロトタイプ開発（Google API、LINE API）</li>
        </ul>
        """
        [[params.experience.list.items]]
        details = """物流アウトソーシングサービスを提供するスタートアップでの開発支援（2022年4月～2022年9月）
        <ul>
          <li>海外発送機能の新規開発（Laravel、FedEx API）</li>
        </ul>
        """
        [[params.experience.list.items]]
        details = """ECサイトを運営するスタートアップでの開発支援（2021年6月～2022年3月）
        <ul>
          <li>ECサイトの追加開発（CakePHP）</li>
          <li>ドメイン駆動設計の支援</li>
        </ul>
        """

        [[params.experience.list]]
        title = "個人開発者"
        dates = "2020年8月～現在"
        [[params.experience.list.items]]
        details = "Webサービス・Webアプリケーションの開発・運営"
        [[params.experience.list.items]]
        details = "OSSの開発"

        [[params.experience.list]]
        title = "Webエンジニア"
        dates = "2016年10月～2020年7月"
        company = "株式会社ホワイトプラス"
        [[params.experience.list.items]]
        details = "PHP・Laravelのテックリード（3年以上）"
        [[params.experience.list.items]]
        details = "ドメイン駆動設計の導入・推進・実践（3年以上）"
        [[params.experience.list.items]]
        details = """継続的インテグレーション・ユニットテスト・静的解析の導入・推進・実践（3年以上）
        <ul>
          <li>[リネットのPHPアプリケーションのCIを10倍速くするためにやったこと](https://qiita.com/ngmy/items/0821d9c56834b6b15a5f)</li>
          <li>[PHPStanによる静的解析をLaravelアプリケーションに導入するためにやったこと](https://qiita.com/ngmy/items/1a8ef21c76d74c1d4dfe)</li>
        </ul>
        """
        [[params.experience.list.items]]
        details = "レガシーコードの改善（3年以上）"

        [[params.experience.list]]
        title = "システムエンジニア"
        dates = "2008年4月～2016年9月"
        company = "株式会社日立ソフトウェアエンジニアリング（現・株式会社日立ソリューションズ）"
        [[params.experience.list.items]]
        details = "月間10億リクエスト、秒間3,000リクエストのニュースサイトのアーキテクチャー設計"
        [[params.experience.list.items]]
        details = "最大10人のプロジェクトのプロジェクトマネージメント（3年以上）"
        [[params.experience.list.items]]
        details = "要件定義から納品までの全工程の開発（5年以上）"











    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "[MoonBoard Search](https://ngmy.github.io/apps/moonboard-search/)"
        meta = "Webアプリケーション"
        tagline = "MoonBoardの課題を検索するためのWebアプリケーション。"
        [[params.projects.list]]
        title = "[Webloyer](https://github.com/ngmy/webloyer)"
        meta = "OSS"
        tagline = "PHP製のデプロイツール「Deployer」のデプロイを管理するためのWebユーザーインターフェイス。"










    [params.information]
        enable = true

        [[params.information.list]]
        title = "資格"
        [[params.information.list.items]]
        details = "2020年：PHP7技術者認定初級試験"
        [[params.information.list.items]]
        details = "2015年：システムアーキテクト試験"
        [[params.information.list.items]]
        details = "2011年：情報セキュリティスペシャリスト試験（現・情報処理安全確保支援士試験）"
        [[params.information.list.items]]
        details = "2011年：Linux Professional Institute Certification Level 1（LPIC-1）"
        [[params.information.list.items]]
        details = "2008年：ソフトウェア開発技術者試験（現・応用情報技術者試験）"
        [[params.information.list.items]]
        details = "2007年：基本情報技術者試験"







    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/ngmy"
        title = "ngmy"
        [[params.social.list]]
        icon = "svg-inline--fa icon-qiita"
        url = "https://qiita.com/ngmy"
        title = "@ngmy"





    [params.footer]
        copyright = "[永宮 悠大](https://ngmy.github.io/)"
