# Page settings

defaultContentLanguage = "ja"

baseURL = "https://ngmy.github.io/resume/"
languageCode = "ja_JP"
title = "職務経歴書（永宮 悠大）"
theme = "hugo-devresume-theme"
googleAnalytics = "G-20TT5CYF3T"






[params]
    author = "永宮 悠大"
    description = "永宮悠大の職務経歴書です。"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "<ruby>永宮<rt>ながみや<rt></ruby> <ruby>悠大<rt>ゆうた</rt></ruby>"
        tagline = "フリーランスWebエンジニア"
        avatar = "profile.png"







    [params.contact]
        enable = true
        location = "東京都"

        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "https://ngmy.github.io/contact/"
        text = "ngmy.github.io/contact"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://ngmy.github.io/"
        text = "ngmy.github.io"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "ハードスキル"
        [[params.skills.list.items]]
        details = "経験分野：Web開発（15年以上）"
        [[params.skills.list.items]]
        details = "設計手法：オブジェクト指向設計（15年以上）、ドメイン駆動設計（5年以上）"
        [[params.skills.list.items]]
        details = "プログラミング言語：PHP（15年以上）、JavaScript（15年以上）"
        [[params.skills.list.items]]
        details = "フレームワーク：Laravel（10年以上）、Livewire（1年以上）、Vue.js（3年以上）"
        [[params.skills.list.items]]
        details = "データベース：MySQL（15年以上）、Redis（10年以上）、Firestore（3年以上）"
        [[params.skills.list.items]]
        details = "Webサーバー：nginx（5年以上）"
        [[params.skills.list.items]]
        details = "クラウドプラットフォーム：AWS（5年以上）、GCP（3年以上）、Heroku（5年以上）、Firebase（3年以上）"
        [[params.skills.list.items]]
        details = "開発支援ツール：Git（10年以上）、GitHub（10年以上）"
        [[params.skills.list.items]]
        details = "テスト・静的解析ツール：PHPUnit（15年以上）、PHPStan（5年以上）"
        [[params.skills.list.items]]
        details = "その他開発環境：Docker（5年以上）、WSL（3年以上）、Linux（15年以上）、Vim（15年以上）"
        [[params.skills.list.items]]
        details = "マネジメント経験：最大10人規模のプロジェクトマネジメント（3年以上）"
        [[params.skills.list.items]]
        details = "開発パート経験：要件定義（10年以上）、設計（15年以上）、実装（15年以上）、テスト（15年以上）、運用（10年以上）"
        [[params.skills.list.items]]
        details = "その他開発経験：アーキテクチャ設計、データベース設計、SQLチューニング"

        [[params.skills.list]]
        title = "ソフトスキル"
        [[params.skills.list.items]]
        details = "課題発見能力、問題解決能力、情報収集能力、洞察力、自走力、プロ意識、粘り強さ"




    [params.education]
        enable = true

        [[params.education.list]]
        degree = "修士（工学）"
        university = "群馬大学 大学院工学研究科 情報工学専攻（現・群馬大学 大学院情報学研究科 情報科学プログラム）"
        dates = "2006年～2008年"
        [[params.education.list]]
        degree = "学士（工学）"
        university = "群馬大学 工学部 情報工学科（現・群馬大学 情報学部 計算機科学プログラム）"
        dates = "2002年～2006年"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "英語"
        level = "ドキュメントが読める"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "クライミング（ボルダリング）、囲碁、Web・OSS開発"








    [params.summary]
        enable = true
        text = "15年以上Web開発に携わる、PHPとオブジェクト指向が好きなフリーランスのWebエンジニア。大手SIerでの大規模システム受託開発と、1→10フェーズのスタートアップでの自社サービス開発の両方を経験。前職ではPHP・Laravelのテックリードを務める。PHP以外にも動的・静的の両言語経験を持ち、大学・大学院でコンピューターサイエンス・ソフトウェア工学を学んだ背景を持つ。アプリケーション設計が特に好きだが、実際に手を動かす実装も好き。仕事をする上で大切にしている価値観は、「仕事を楽しむこと」と「納期と品質の期待値を外さず顧客に価値を届けること」。"







    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "フリーランスWebエンジニア"
        dates = "2021年6月～現在"
        [[params.experience.list.items]]
        details = """SaaS/FMS（フリーランスマネジメントシステム）系企業（2023年10月～現在）
        <ul>
          <li>アプリケーションアーキテクチャ・リファクタリング方針の策定</li>
          <li>品質・開発標準の策定（コーディング規約、テストガイドライン）</li>
          <li>開発プロセス改善（CI/ユニットテスト/静的解析の導入・推進）</li>
        </ul>
        """
        [[params.experience.list.items]]
        details = """SaaS/CRM系スタートアップ（2022年10月～2023年9月）
        <ul>
          <li>CTO直下でのPoC開発支援（Laravel）</li>
        </ul>
        """
        [[params.experience.list.items]]
        details = """物流系スタートアップ（2022年4月～2022年9月）
        <ul>
          <li>WMSの開発支援（Laravel）</li>
        </ul>
        """
        [[params.experience.list.items]]
        details = """EC系スタートアップ（2021年6月～2022年3月）
        <ul>
          <li>ECサイトの開発支援（Laravel）</li>
          <li>ドメイン駆動設計の導入支援</li>
        </ul>
        """

        [[params.experience.list]]
        title = "個人開発者"
        dates = "2020年8月～現在"
        [[params.experience.list.items]]
        details = "Webサービス・Webアプリの開発・運営"
        [[params.experience.list.items]]
        details = "OSSの開発"

        [[params.experience.list]]
        title = "Webエンジニア"
        dates = "2016年10月～2020年7月"
        company = "株式会社ホワイトプラス"
        [[params.experience.list.items]]
        details = "テックリード（PHP/Laravel）：3年以上"
        [[params.experience.list.items]]
        details = "ドメイン駆動設計（導入・推進・実践）：3年以上"
        [[params.experience.list.items]]
        details = "開発プロセス改善（CI/ユニットテスト/静的解析の導入・推進・実践）：3年以上"
        [[params.experience.list.items]]
        details = "レガシーコード改善：3年以上"

        [[params.experience.list]]
        title = "システムエンジニア"
        dates = "2008年4月～2016年9月"
        company = "株式会社日立ソフトウェアエンジニアリング（現・株式会社日立ソリューションズ）"
        [[params.experience.list.items]]
        details = "大規模トラフィックサイトのアーキテクチャ設計（月間10億リクエスト/秒間3,000リクエスト）"
        [[params.experience.list.items]]
        details = "プロジェクトマネジメント（最大10人規模）：3年以上"
        [[params.experience.list.items]]
        details = "システム開発全工程の担当（要件定義～納品）：5年以上"











    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "[MoonBoard Search](https://ngmy.github.io/apps/moonboard-search/)"
        meta = "Webアプリ"
        tagline = "MoonBoardの課題検索Webアプリ。"
        [[params.projects.list]]
        title = "[Webloyer](https://github.com/ngmy/webloyer)"
        meta = "OSS"
        tagline = "Deployerのデプロイ管理用Web画面。"










    [params.information]
        enable = true

        [[params.information.list]]
        title = "資格"
        [[params.information.list.items]]
        details = "2020年：PHP7技術者認定初級試験"
        [[params.information.list.items]]
        details = "2015年：システムアーキテクト試験"
        [[params.information.list.items]]
        details = "2011年：情報セキュリティスペシャリスト試験（現・情報処理安全確保支援士試験）"
        [[params.information.list.items]]
        details = "2011年：Linux Professional Institute Certification Level 1（LPIC-1）"
        [[params.information.list.items]]
        details = "2008年：ソフトウェア開発技術者試験（現・応用情報技術者試験）"
        [[params.information.list.items]]
        details = "2007年：基本情報技術者試験"







    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/ngmy"
        title = "ngmy"





    [params.footer]
        copyright = "[永宮 悠大](https://ngmy.github.io/)"
