# Page settings

defaultContentLanguage = "ja"

baseURL = "https://ngmy.github.io/resume/"
languageCode = "ja"
title = "職務経歴書（永宮 悠大）"
theme = "hugo-devresume-theme"
googleAnalytics = "G-20TT5CYF3T"






[params]
    author = "永宮 悠大"
    description = "ngmy（永宮悠大）の職務経歴書です。"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "<ruby>永宮<rt>ながみや<rt></ruby>&nbsp;<ruby>悠大<rt>ゆうた</rt></ruby>"
        tagline = "Webエンジニア"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "東京都"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:09057595237"
        text = "090 5759 5237"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:y.nagamiya+work@gmail.com"
        text = "y.nagamiya+work@gmail.com"
        [[params.contact.list]]
        icon = "fab fa-skype"
        url = "skype:live:y.nagamiya?call"
        text = "live:y.nagamiya"
        [[params.contact.list]]
        icon = "svg-inline--fa icon-pay-career"
        url = "https://pay-career.com/spot_request/2033945709/"
        text = "pay-career.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://ngmy.github.io/"
        text = "ngmy.github.io"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "テクニカル"
        [[params.skills.list.items]]
        details = "<strong>プログラミング言語：</strong>PHP、JavaScript、HTML・CSS、Bash"
        [[params.skills.list.items]]
        details = "<strong>フレームワーク：</strong>PHP（Laravel、CakePHP、Slim）、JavaScript（Vue.js、React、Angular）、HTML・CSS（Bootstrap）"
        [[params.skills.list.items]]
        details = "<strong>ライブラリー：</strong>PHP（Symfonyコンポーネント）、JavaScript（jQuery）"
        [[params.skills.list.items]]
        details = "<strong>データベース：</strong>SQL（MySQL）、NoSQL（Redis、memcached、Firestore）"
        [[params.skills.list.items]]
        details = "<strong>Webサーバー：</strong>nginx、Apache"
        [[params.skills.list.items]]
        details = "<strong>テストツール：</strong>PHP（PHPUnit）、E2E（Selenium）"
        [[params.skills.list.items]]
        details = "<strong>静的解析ツール：</strong>PHP（PHPStan、Psalm、PHP_CodeSniffer、PHP CS Fixer、PHPMD）"
        [[params.skills.list.items]]
        details = "<strong>仮想化ツール：</strong>Docker、Kubernetes"
        [[params.skills.list.items]]
        details = "<strong>継続的インテグレーションサービス：</strong>GitHub Actions、CircleCI、Travis CI"
        [[params.skills.list.items]]
        details = "<strong>クラウドサービス：</strong>AWS、GCP、Heroku、Firebase"
        [[params.skills.list.items]]
        details = "<strong>開発環境：</strong>WSL 2、Mac、Linux"
        [[params.skills.list.items]]
        details = "<strong>その他：</strong>Git、GitHub、Vim"

        [[params.skills.list]]
        title = "プロフェッショナル"
        [[params.skills.list.items]]
        details = "Web開発（特にサーバーサイド開発）"
        [[params.skills.list.items]]
        details = "オブジェクト指向設計、ドメイン駆動設計"
        [[params.skills.list.items]]
        details = "アーキテクチャー設計"
        [[params.skills.list.items]]
        details = "SQL、データベース設計"
        [[params.skills.list.items]]
        details = "継続的インテグレーション・ユニットテスト・静的解析の仕組みづくり"
        [[params.skills.list.items]]
        details = "リファクタリング、レガシーコード改善"
        [[params.skills.list.items]]
        details = "ソースコードリーディング、既存システム理解"
        [[params.skills.list.items]]
        details = "要件定義、工数見積、プロジェクトマネージメント"
        [[params.skills.list.items]]
        details = "ドキュメント作成"





    [params.education]
        enable = true

        [[params.education.list]]
        degree = "修士（工学）"
        university = "群馬大学 大学院工学研究科 情報工学専攻"
        dates = "2006年～2008年"
        [[params.education.list]]
        degree = "学士（工学）"
        university = "群馬大学 工学研究科 情報工学科"
        dates = "2002年～2006年"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "日本語"
        level = "母語語"
        [[params.languages.list]]
        name = "英語"
        level = "ドキュメントが読める"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "クライミング"
        [[params.interests.list]]
        name = "囲碁"








    [params.summary]
        enable = true
        text = "10年以上の経験を持ち、Webサービスと業務システムの両方の開発経験を持つ、PHPとオブジェクト指向設計を愛するWebエンジニア。大手システムインテグレーターでのかっちりとした受託開発と、1→10フェーズのスタートアップでのスピード感のある自社サービス開発という両方の経験を持つ。前職ではPHPとLaravelのテックリードを務め技術面で開発をリードした。PHP以外にも動的型付けと静的型付けの両方のプログラミング言語を使用した経験と、大学・大学院でプログラミングとコンピューターサイエンスを学んだバックグラウンドを持つ。PHPの技術で開発をリードでき、大所高所の設計から細部の開発までのすべてに携われるポジションで、PHPとオブジェクト指向設計を使用してWeb開発の仕事をしたい。最大10人のプロジェクトマネージメント経験も持つが、マネージメントより自分で手を動かす仕事をしたい。好きで得意な仕事は「複雑な業務をシステムに落とし込むこと」と「継続的インテグレーション・ユニットテスト・静的解析などの品質・生産性を向上させるための仕組みづくり」。仕事をする上で大切にしていることは「自分が楽しむこと」と「納期と品質の期待値を外すことなく顧客に価値を届けること」。"








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "フリーランス・個人開発者"
        dates = "2020年～現在"
        details = "フリーランスとして活動しながら、個人開発に取り組んでいる。"
        [[params.experience.list.items]]
        details = "<strong>フリーランス：</strong>スタートアップにてECサイトの開発に従事し、サーバーサイド（PHP、CakePHP）からフロントエンド（JavaScript、Vue.js）の開発を行いながら、チームへPHP・ユニットテスト・静的解析・ドメイン駆動設計などのノウハウの共有も行っている"
        [[params.experience.list.items]]
        details = "<strong>個人開発者：</strong>PWAの開発（Vue.js、Firebase、Firestore）や、GitHubアプリ（PHP、Slim、Heroku）の開発を行っている"

        [[params.experience.list]]
        title = "テックリード"
        dates = "2016年～2020年"
        company = "株式会社ホワイトプラス"
        details = "1→10フェーズのスタートアップ。PHPとLaravelの技術で開発をリードして、事業の成長を支えるためにシステムを発展させる役割を担った。"
        [[params.experience.list.items]]
        details = "システムの将来像の策定、PHPとLaravelの継続的なバージョンアップ、PHPコードやMySQLデータベースのリファクタリング、ドメイン駆動設計による設計の改善をすることで、システムを発展させた"
        [[params.experience.list.items]]
        details = "継続的インテグレーション・ユニットテスト・静的解析の仕組みを作り、さらに[ビルドを10倍高速化](https://qiita.com/ngmy/items/0821d9c56834b6b15a5f)したり、当時はまだ他社事例が少なかった[PHPStanを導入](https://qiita.com/ngmy/items/1a8ef21c76d74c1d4dfe)することで、品質・生産性を向上させた"
        [[params.experience.list.items]]
        details = "PHPの実行環境をDocker化して、インフラエンジニアと協力してKubernetesを導入することで、インフラの柔軟性を向上させた"
        [[params.experience.list.items]]
        details = "生産管理システムや原価管理システムをPHPとLaravelを使用してドメイン駆動設計で開発することで、システムを洗練させるとともに事業の成長を支えた"
        [[params.experience.list.items]]
        details = "生産管理システムのうち、現場作業員が使用する画面をJavaScriptとVue.jsやReactを使用して開発することで、生産現場の生産性を向上させた"
        [[params.experience.list.items]]
        details = "エンジニアの採用面談を担当し、面談時のペアプログラミングを提案・実践することで、即戦力となるエンジニアの採用に成功した"
        [[params.experience.list.items]]
        details = "新人教育プログラムの作成・実施や新人のメンターを担当することで、新人を育成した"
        [[params.experience.list.items]]
        details = "エンジニアが不足していた時期には、1人で1サービスの注文フォーム・販売管理システム・生産管理システム・問い合わせ管理システムなどのサーバーサイド（PHP、Laravel）からフロントエンド（JavaScript、Vue.js、React、Angular、jQuery）までを開発することで、事業の継続を支えた"

        [[params.experience.list]]
        title = "プレイングマネージャー"
        dates = "2013年～2016年"
        company = "株式会社日立ソフトウェアエンジニアリング（現・株式会社日立ソリューションズ）"
        details = "大手システムインテグレーター。受託開発したニュースサイト（後述の経歴で説明）の運用・保守に従事し、プロジェクトマネージメントをしながら技術面で開発をリードする役割を担った。これには顧客のサービスを継続的に成長させ、運用・保守を継続してもらうことも含まれた。"
        [[params.experience.list.items]]
        details = "顧客との折衝や最大10人のプロジェクトマネージメントをすることで、3年間で月間ページビュー数を1.8億から10億へ成長させ、その間の運用・保守を任せてもらうことに成功した"
        [[params.experience.list.items]]
        details = "リソースやレスポンスの監視の設計・実装を行い、必要に応じて性能改善やリソース増強をすることで、サービスが成長する間もレスポンスタイム200ミリ秒以下と安定した運用を実現した"
        [[params.experience.list.items]]
        details = "チームとともにPHPやJavaScriptのコードを書き、またチームが書いたコードをレビューすることで、開発をリードした"

        [[params.experience.list]]
        title = "アーキテクト"
        dates = "2012年～2013年"
        company = "株式会社日立ソフトウェアエンジニアリング（現・株式会社日立ソリューションズ）"
        details = "大手システムインテグレーター。ニュースサイトの受託開発に従事し、「高負荷・高トラフィックに耐えられること」「スケーラビリティーがあること」「既存の別ニュースサイトと記事データを共通化すること」という3つの要件を満たすアーキテクチャーを設計する役割を担った。"
        [[params.experience.list.items]]
        details = "Webサーバー・APIサーバー・データベースサーバーの3層からなり、WebサーバーにおいてAPIのレスポンスをmemcachedにキャッシュするアーキテクチャを設計し、PHPとCodeIgniterを使用して開発することで、「秒間3,000リクエストでレスポンスタイム200ミリ秒以下の性能」「層ごとのスケーラビリティー」「APIを介することによる記事データの共通化」を実現した"
        [[params.experience.list.items]]
        details = "設計の要となるAPIリクエストまわりとmemcachedまわりの機能を実装してチームに提供し、またチームが書いたコードが設計から逸脱しないようにレビューすることで、設計を守り、形にすることに成功した"
        [[params.experience.list.items]]
        details = "継続的インテグレーション・ユニットテスト・静的解析の仕組みを作ることで、品質・生産性を向上させた"

        [[params.experience.list]]
        title = "サーバーサイドエンジニア"
        dates = "2008年～2012年"
        company = "株式会社日立ソフトウェアエンジニアリング（現・株式会社日立ソリューションズ）"
        details = "大手システムインテグレーター。様々なWebシステムの受託開発に従事し、プロジェクトの一員としてシステムを開発する役割を担った。"
        [[params.experience.list.items]]
        details = "Q&Aコミュニティーサービス（PHP）、健康機器測定データプラットフォームおよびプラットフォームと連携する健康支援サービス（Java）、ケーブルテレビ局の顧客管理システム（Perl）、検索エンジンの形態素解析モジュール（C、Ruby）などを開発した"
        [[params.experience.list.items]]
        details = "プログラミング以外にも要件定義から納品までの全工程を経験した"











    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "[Webloyer](https://github.com/ngmy/webloyer)"
        meta = "オープンソース"
        tagline = "PHP製のデプロイツール「Deployer」のWebユーザーインターフェイス。Laravelを使用してドメイン駆動設計で開発している。"

        [[params.projects.list]]
        title = "[PHP WebDAV Client](https://github.com/ngmy/l4-dav)"
        meta = "オープンソース"
        tagline = "PHP用のWebDAVクライアント。PSR-7（HTTPメッセージインターフェイス）、PSR-17（HTTPファクトリー）、PSR-18（HTTPクライアント）を使用して開発している。"










    [params.information]
        enable = true

        [[params.information.list]]
        title = "資格"
        [[params.information.list.items]]
        details = "2020年：PHP7技術者認定初級試験"
        [[params.information.list.items]]
        details = "2015年：システムアーキテクト試験"
        [[params.information.list.items]]
        details = "2011年：情報セキュリティスペシャリスト試験（現・情報処理安全確保支援士試験）"
        [[params.information.list.items]]
        details = "2011年：Linux Professional Institute Certification Level 1（LPIC-1）"
        [[params.information.list.items]]
        details = "2008年：ソフトウェア開発技術者試験（現・応用情報技術者試験）"
        [[params.information.list.items]]
        details = "2007年：基本情報技術者試験"

        [[params.information.list]]
        title = "人となり"
        [[params.information.list.items]]
        details = "[【社員インタビュー#エンジニア】WEBだけでなくリアルなサービスが絡んでいるのが面白い | ホワプラSTYLE](https://style.wh-plus.co.jp/interview-nagamiyayuta/)"







    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/ngmy"
        title = "ngmy"
        [[params.social.list]]
        icon = "svg-inline--fa icon-qiita"
        url = "https://qiita.com/ngmy"
        title = "@ngmy"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "https://twitter.com/ngmy"
        title = "@ngmy"





    [params.footer]
        copyright = "[永宮 悠大](https://ngmy.github.io/)"
